### ISSUE TITLE
bionic builder description should include .NET

### ISSUE THREAD

**Issue by ekcasey** [paketo-buildpacks/builder#10]
The order for the `cloudfoundry/cnb:bionic` builder includes `dotnet-core` buildpacks, but the list of languages in the description does not include .NET.

```
pack inspect-builder cloudfoundry/cnb:bionic
Inspecting builder: cloudfoundry/cnb:bionic

REMOTE:

Description: Ubuntu bionic base image with buildpacks for Java, NodeJS and Golang
```

**Comment by ryanmoran** [comment]
Full: https://github.com/paketo-buildpacks/full-builder/pull/88
Base: https://github.com/paketo-buildpacks/base-builder/pull/44
Tiny: https://github.com/paketo-buildpacks/tiny-builder/pull/29

**Comment by fg-j** [comment]
Closing since each of the above linked pull requests have been merged.
