### ISSUE TITLE
Showing wrong created time for base-platform-api-0.3 tag

### ISSUE THREAD

**Issue by piyushpcegarg** [paketo-buildpacks/builder#20]
When using gcr.io/paketo-buildpacks/builder to build docker image for spring boot application, it shows created time as 40 years ago.

![wrong_created_time](https://user-images.githubusercontent.com/11294278/82724380-54af9300-9cf3-11ea-9abd-f4a81be55841.png)

**Comment by sclevine** [comment]
This is intentional. The pack CLI zeros timestamps when building builders, buildpackages, and apps so that the image digests are reproducible.

**Comment by kvedurmu** [comment]
Closing this out. Feel free to post a message on the Paketo slack (slack.paketo.io) for questions/issues such as this so we can help sort it out faster 😃
