### ISSUE TITLE
builders should have run-image-mirrors for dockerhub stack images

### ISSUE THREAD

**Issue by martyspiewak** [paketo-buildpacks/builder#21]
Paketo stack images are published to dockerhub at `paketobuilpacks/<stack>:<run/build>`

The builders should list these stack images as run-image-mirrors

**Comment by mdelillo** [comment]
This was done as a param in CI [here](https://github.com/cloudfoundry/buildpacks-ci/commit/af3d5671778e4e12634bbb7668f4792b55752846).

```
$ pack inspect-builder gcr.io/paketo-buildpacks/builder:base | grep -A3 'Run Images:'
Run Images:
  gcr.io/paketo-buildpacks/run:base-cnb
  registry.hub.docker.com/paketobuildpacks/run:base-cnb

--
Run Images:
  gcr.io/paketo-buildpacks/run:base-cnb
  registry.hub.docker.com/paketobuildpacks/run:base-cnb
```
