### ISSUE TITLE
Can Ruby be added to cflinuxfs3 please?

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/builder#5]

**Comment by zmackie** [comment]
@drnic Are you asking for us to add the ruby-cnbs? I think that's on the roadmap somewhere but they're not really ready for prime-time (which inclusion on the builder implies).

**Comment by drnic** [comment]
Yeah, I guess my request assumed that the set of ruby related CNBs were functional :)

**Comment by zmackie** [comment]
We'll keep you update on progress for those CNBs. We're humming along so it won't take very long, I imagine.

**Comment by dfreilich** [comment]
I'll close this for now. It's definitely not high on our priority list (dotnet, go and python are all higher in priority), but we're definitely planning to get to it over the next few months!
