### ISSUE TITLE
Nominating @ForestEckhardt as a Builder subteam maintainer

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/builder#51]
@ForestEckhardt recently contributed the [RFC to add Procfile to the Tiny builder](https://github.com/paketo-buildpacks/builder/pull/49). He has also advocated for improved builders documentation and contributed to the automation of the Builder repos. See:
- https://github.com/paketo-buildpacks/full-builder/pull/86
- https://github.com/paketo-buildpacks/tiny-builder/issues/24
- https://github.com/paketo-buildpacks/base-builder/issues/40

@ekcasey - seeking a vote from you.

**Comment by ekcasey** [comment]
Approve!

(cc @fg-j @ForestEckhardt)

**Comment by fg-j** [comment]
With a supermajority of current maintainers (2/3), @ForestEckhardt welcome to the subteam! @ryanmoran Can you do the various permissioning things?

**Comment by ryanmoran** [comment]
@fg-j done!
