### ISSUE TITLE
docker `paketobuildpacks/builder` -created 41 years ago?

### ISSUE THREAD

**Issue by Divine1** [paketo-buildpacks/builder#53]
i was playing around with building image for a demo springboot(2.5.0) project using docker
`./mvnw spring-boot:build-image`

Why does `paketobuildpacks/builder` show `created 41 years ago` in the output of `docker images` command? was it created 41 years ago?

![image](https://user-images.githubusercontent.com/10482177/120431778-96f3c180-c396-11eb-8b17-85baadc77a73.png)

**Comment by fg-j** [comment]
Hi there. The Paketo builders are created using the `pack` CLI. For that reason, the image metadata is affected by the "consequences and caveats" [listed here on the CNB documentation site](https://buildpacks.io/docs/reference/reproducibility/#consequences-and-caveats).

It was not, in fact, created 41 years ago. Releases of the Paketo base builder are published [on this repo](https://github.com/paketo-buildpacks/base-builder/releases). We release them a few times a week 🙂

**Comment by Divine1** [comment]
@fg-j can this be used in production? is it production-ready?

**Comment by fg-j** [comment]
Paketo buildpacks, stacks, and builders are designed to build apps into production-ready container images, by default.

If you're interested in chatting with folks who are currently using and developing Paketo buildpacks, builders, and stacks, I encourage you to [join our Slack](https://slack.paketo.io/)!

**Comment by Divine1** [comment]
@fg-j thank you for the clarification
