### ISSUE TITLE
build doesn't have access to plan?

### ISSUE THREAD

**Issue by loosebazooka** [paketo-buildpacks/builder#9]
I was going through the buildpacks tutorial (caching specifically: https://buildpacks.io/docs/create-buildpack/caching/) and I can't seem to access the plan from a `build` after setting in a `detect`.

Both `$3` and `stdin` seem to be empty. On the otherhand using the heroku builder seems to work at least with stdin (though the file referenced by $3 is empty here too)

The spec seems to indicate that a plan should be available: https://github.com/buildpack/spec/blob/master/buildpack.md#build

Am I missing something here?

**Comment by zmackie** [comment]
Closing now that the point of contact is clearer.
